monitor=eDP-1,preferred,auto,1

$mainMod = SUPER
$menu = wofi --show drun --allow-images
$fileManager = nautilus
$terminal = ghostty

exec-once = awww-daemon & waybar & swaync & hypridle & nm-applet & swayosd-server
exec-once = sleep 0.5 && awww img ~/.config/backgrounds/dune.jpeg --transition-type fade

bind = $mainMod, return, exec, $terminal
bind = $mainMod, C, killactive
bind = $mainMod, M, exit
bind = $mainMod, space, exec, $menu
bind = $mainMod, E, exec, $fileManager
bind = $mainMod, V, togglefloating
bind = $mainMod, F, fullscreen
bind = , PRINT, exec, hyprshot -m window
bind = shift, PRINT, exec, hyprshot -m region
bind = $SUPER_SHIFT, l, exec, hyprlock


# control volume, fn + up/down arrow
# control brightness, fn + left/right
bind = , XF86AudioRaiseVolume, exec, swayosd-client --output-volume raise
bind = , XF86AudioLowerVolume, exec, swayosd-client --output-volume lower
bind = , XF86AudioMute, exec, swayosd-client --output-volume mute-toggle
bind = , XF86MonBrightnessUp, exec, swayosd-client --brightness raise
bind = , XF86MonBrightnessDown, exec, swayosd-client --brightness lower

bind = $mainMod, h, movefocus, l
bind = $mainMod, j, movefocus, d
bind = $mainMod, k, movefocus, u
bind = $mainMod, l, movefocus, r

# switch to workspace
bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5
bind = $mainMod, 6, workspace, 6
bind = $mainMod, 7, workspace, 7
bind = $mainMod, 8, workspace, 8

# move active window to workspace
bind = $mainMod SHIFT, 1, movetoworkspace, 1
bind = $mainMod SHIFT, 2, movetoworkspace, 2
bind = $mainMod SHIFT, 3, movetoworkspace, 3
bind = $mainMod SHIFT, 4, movetoworkspace, 4
bind = $mainMod SHIFT, 5, movetoworkspace, 5
bind = $mainMod SHIFT, 6, movetoworkspace, 6
bind = $mainMod SHIFT, 7, movetoworkspace, 7
bind = $mainMod SHIFT, 8, movetoworkspace, 8

# SUPER + left click + drag to move window
bindm = $mainMod, mouse:272, movewindow

# SUPER + right click + drag to resize window
bindm = $mainMod, mouse:273, resizewindow

general {
    layout = dwindle
    gaps_in = 5
    gaps_out = 10
}

decoration {
    rounding = 8
}

dwindle {
    force_split = 2
}

input {
    touchpad {
        natural_scroll = true
    }
}

cursor {
    no_hardware_cursors = false
}

decoration {
    rounding = 8
    blur {
        enabled = true
        size = 8
        passes = 2
        vibrancy = 0.1696
    }
}

layerrule = blur on, match:namespace swaync-control-center
layerrule = blur on, match:namespace swaync-notification-window
layerrule = ignore_alpha 0.1, match:namespace swaync-control-center
layerrule = ignore_alpha 0.1, match:namespace swaync-notification-window

layerrule = blur on, match:namespace wofi
layerrule = ignore_alpha 0.1, match:namespace wofi
